import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className="bg-[url('https://cdn.dooca.store/925/products/whatsapp-image-2021-02-12-at-111933_640x640+fill_ffffff.jpeg?v=1613139636&webp=0')]"}>{children}</body>
    </html>
  )
}
